### ISSUE TITLE
Current state

### ISSUE THREAD

**Issue by davidhealey** [cybermaggedon/gnucash-uk-vat#5]
Thanks for this, looks like just what I need now I'm being forced onto MTD.

Is the software still working with the latest changes from HMRC? Is it being actively kept up to date?

**Comment by cybermaggedon** [comment]
Hi @davidhealey , yes it still works and is up-to-date, I filed VAT a couple of weeks back. I've tested with gnucash module on Linux, and piecash module on Macbook.  Email me mark@cyberapocalypse.co.uk if you want a client key to try it out.

**Comment by davidhealey** [comment]
Thanks. I'll take a look at it in the next few weeks when I come to doing my return.
