### ISSUE TITLE
Cannot authenticate

### ISSUE THREAD

**Issue by MichaelBScott** [cybermaggedon/gnucash-uk-vat#8]
I just found some time to look at this again so I have resumed attempting to get this working in the sandbox so I can request a production id, but I am unable to proceed past the authenticate step.

When I go to the provided url (I have omitted the client id):

https://test-www.tax.service.gov.uk/oauth/authorize?response_type=code&client_id=********&scope=read%3Avat%2Bwrite%3Avat&redirect_uri=http%3A%2F%2Flocalhost%3A9876%2Fauth

I get the response:

{"error":"invalid_request","error_description":"redirect_uri is invalid"}

Do you have any idea how I can proceed?

**Comment by cybermaggedon** [comment]
Ah yeh, you have to register the redirect URI with your sandbox application. If you go to the sandbox application, and click on the application you registered, on the left-hand side is a list click Redirect URIs.  And add...
```
http://localhost:9876
```
Exactly as it is above, no trailing slash.

FYI the redirect URI is the URL that your browser gets redirected to with an auth key, and we use http://localhost:9876.  You have to add that as a permitted redirect URI for HMRC's identity service to grant a token.

**Comment by MichaelBScott** [comment]
Thank you that resolved the authentication issue.

I have progressed through and successfully submitted a VAT return.
However, clicking on the Post VAT bill button shows the following message and I cannot progress to the Summary page:
'UI' object has no attribute 'ui'

I'm not sure if this is the cause but the VAT period it requested had zero for both VAT due and VAT reclaimed.

**Comment by cybermaggedon** [comment]
No, I think that's a bug in the code, I'll take a look later.

**Comment by MichaelBScott** [comment]
Ok, thank you.

**Comment by cybermaggedon** [comment]
Hey @MichaelBScott thanks for reporting this, I've taken a look at bill posting. It all broke when I added the piecash support a while back.

The major issue here is that piecash doesn't support vendors bill posting at the moment. I think the best tactic for now is to take out the bill posting rather than leave a half-working function in place. I've taken this out from the CLI and --assist workflows.

**Comment by MichaelBScott** [comment]
I have installed the latest version, but now I get errors when clicking next after selecting a gnucash file when using piecash (see below).
I can progress past this point by selecting the gnucash option and I can authenticate, but it now says the VRN is not valid.

Traceback (most recent call last):
  File "~/.local/lib/python3.10/site-packages/gnucash_uk_vat/assist.py", line 772, in prepare
    self.acc_setup.configure()
  File "~/.local/lib/python3.10/site-packages/gnucash_uk_vat/assist.py", line 222, in configure
    acct_list = accts.get_accounts()
  File "~/.local/lib/python3.10/site-packages/gnucash_uk_vat/accounts_piecash.py", line 93, in get_accounts
    for v in acct.children():
  File "~/.local/lib/python3.10/site-packages/piecash/kvp.py", line 75, in __getitem__
    assert not isinstance(
AssertionError: You are accessing slots with an integer (=0) while a string is expected
~/.local/lib/python3.10/site-packages/gnucash_uk_vat/assist.py:611: RuntimeWarning: coroutine 'Vat.get_auth' was never awaited
  self.vat.get_auth(code)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by cybermaggedon** [comment]
Hey @MichaelBScott I think that's my checkin 2a3f5b which introduced the problem.  Apologies for that, I'll take a look tomorrow.

You might have more luck with v1.3 / 8de921.

**Comment by MichaelBScott** [comment]
HI @cybermaggedon I tried that version.
I still get the same error using piecash.
With gnucash I can authenticate, but when I click submit VAT return I get:
'UI' object has no attribute 'vat_return'

In the terminal it shows:
RuntimeError: Can't locate account 'VAT:Output:Sales'

However, that account does exist in the gnucash file.
It has a sub-account for "Standard Rate VAT"

**Comment by cybermaggedon** [comment]
I've fixed the error `You are accessing slots with an integer (=0) while a string is expected`

I've had to restructure some of the auth code to get it to play nice in another system, and that broke --assist,
I'll take a look in a bit.

I think, if you can run the auth on CLI...
```gnucash-uk-vat --config ... --auth ... --authenticate```
then the resultant auth file should be good to use until I fix the asyncio properly.

**Comment by cybermaggedon** [comment]
@MichaelBScott the latest commit (d7dfca) fixes the asyncio problem with assist. Could you give that a go?

**Comment by cybermaggedon** [comment]
Just checked, it works for me with the HMRC sandbox

**Comment by MichaelBScott** [comment]
HI @cybermaggedon
I have just tried the latest version using piecash and it all appears to be working.

Thank you
